data1 <- read.table("household_power_consumption.txt", nrows = 1, header = FALSE, sep =';', stringsAsFactors = FALSE)
data2("household_power_consumption.txt", skip = 2, header = FALSE, sep =';')
colnames( data2 ) <- unlist(data1)
data<-subset(powerdata,powerdata$Date=="1/2/2007" | powerdata$Date =="2/2/2007")

data$DateTime <- strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(1:nrow(data),data$Sub_metering_1,type='l',xlab='',ylab='Energy Submetering',labels=FALSE,xaxt="n")
axis(1,at = c(1,1440,2880), labels=c('Thu','Fri','Sat'))
#axis(1,at = c(1,1440,2880), labels=c('Thu','Fri','Sat'))
lines(1:nrow(data),as.numeric(data$Sub_metering_2),col='red')
lines(1:nrow(data),as.numeric(data$Sub_metering_3),col='blue')
legend("topright", lty=1, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"))

dev.off()
